version: '3.9'

services:
  livesen-storage:
    image: postgis/postgis:latest
    container_name: livesen-storage
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: livesen
      POSTGRES_USER: livesen
      POSTGRES_PASSWORD: livesen
    volumes:
      - ./.docker/data/store:/var/lib/postgresql/data

  livesen-backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: livesen-backend
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 2204:2204
    volumes:
      - ./.docker/backend.json:/livesen/config.json:ro
      - ./.docker/data/download:/livesen/data/download
      - ./.docker/data/recommend:/livesen/data/recommend
      - ./.docker/data/ndvi:/livesen/data/ndvi
      - ./.docker/data/category:/livesen/data/category
    depends_on:
      - livesen-storage
  
  livesen-frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    container_name: livesen-frontend
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 3000:3000
    env_file:
      - ./.docker/frontend.conf
  
  livesen-proxy:
    build: 
      context: ./proxy
      dockerfile: dockerfile
    container_name: livesen-proxy
    restart: unless-stopped
    networks: 
      - livesen-network
    ports: 
      - 8080:80
    volumes:
      - ./.docker/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - livesen-backend
      - livesen-frontend
  
networks:
  livesen-network:
    driver: bridge
