version: '3.9'

services:
  livesen-storage:
    image: postgis/postgis:latest
    container_name: livesen-storage
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: livesen
      POSTGRES_USER: livesen
      POSTGRES_PASSWORD: livesen
    volumes:
      - ./.docker/data/store:/var/lib/postgresql/data

  livesen-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: livesen-backend
    networks:
      - livesen-network
    ports:
      - 2204:2204
    volumes:
      - ./.docker/.backend:/livesen/config.json:ro
      - ./.docker/data/download:/livesen/data/download
      - ./.docker/data/ndvi:/livesen/data/ndvi
    depends_on:
      - livesen-storage
  
  livesen-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: livesen-frontend
    networks:
      - livesen-network
    ports:
      - 3000:3000
    env_file:
      - ./.docker/.frontend
  
  livesen-proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: livesen-proxy
    restart: unless-stopped
    networks: 
      - livesen-network
    ports: 
      - 8080:80
    depends_on:
      - livesen-backend
      - livesen-frontend
  
  livesen-recommendation:
    build: 
      context: ./recommendation
      dockerfile: Dockerfile
    container_name: livesen-recommendation
    restart: unless-stopped
    networks: 
      - livesen-network
    ports:
      - 1998:1998
    volumes:
      - ./.docker/.recommendation:/livesen/config.json:ro
      - ./.docker/data/model:/livesen/data/model
      - ./.docker/data/category:/livesen/data/category
    depends_on:
      - livesen-storage
  
networks:
  livesen-network:
    driver: bridge
