version: '3.9'

services:
  livesen-storage:
    image: postgis/postgis:latest
    container_name: livesen-storage
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: livesen
      POSTGRES_USER: livesen
      POSTGRES_PASSWORD: livesen
    volumes:
      - ./.docker/private_data/store:/var/lib/postgresql/data

  livesen-notifier:
    image: redis:latest
    container_name: livesen-notifier
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "livesen"]

  livesen-backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: livesen-backend
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 2204:2204
    volumes:
      - ./.docker/backend.json:/livesen/config.json:ro
      - ./.docker/private_data/ndvi:/livesen/data/ndvi
      - ./.docker/private_data/measurement:/livesen/data/measurement
      - ./.docker/public_data/recommend:/livesen/data/recommend
      - ./.docker/public_data/category:/livesen/data/category
    depends_on:
      - livesen-storage
      - livesen-notifier
  
  # # Uncomment the 'livesen-osmap' config for OSM local setup
  # livesen-osmap:
  #   image: overv/openstreetmap-tile-server
  #   container_name: livesen-osmap
  #   networks:
  #     - livesen-network
  #   ports:
  #     - 1998:80
  #   volumes:
  #     - ./.docker/data/osmap:/data/database/
  #   command: ["run"]
  
  livesen-frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    container_name: livesen-frontend
    restart: unless-stopped
    networks:
      - livesen-network
    ports:
      - 3000:3000
    env_file:
      - ./.docker/frontend.conf

  livesen-proxy:
    image: nginx:latest
    container_name: livesen-proxy
    restart: unless-stopped
    networks: 
      - livesen-network
    ports: 
      - 8080:8080
    volumes:
      - ./.docker/proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - livesen-backend
      - livesen-frontend
  
networks:
  livesen-network:
    driver: bridge
