FROM python:3.11

ENV GDAL_VERSION 3.8.0

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  libgdal-dev \
  gdal-bin \
  && rm -rf /var/lib/apt/lists/*

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

WORKDIR /livesen

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# TODO: complete the production config ...